### ISSUE TITLE
TRG 5.11 Upgradeability

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-cd#132]
No upgrade testing availble as it's commented in workflow file:
https://github.com/eclipse-tractusx/portal-cd/blob/52812dc8cf84c66417984f88366c84f45eb713c7/.github/workflows/portal-chart-test.yaml#L97-L105

**Comment by evegufy** [comment]
@carslen Due to the [major version upgrade in the subchart](https://github.com/eclipse-tractusx/portal-cd/blob/portal-1.7.0-RC4/CHANGELOG.md?plain=1#L68) of the subchart, this upgrade step will inevitability fail so I disabled it until the release of the 1.7.0 version. I mentioned this in the office hour as something to consider for this TRG.
