### ISSUE TITLE
QG4: TRG 7.02 - License and Copyright header

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/portal-cd#71]
Hi @evegufy,

Testing Quality Guideline: TRG 7.02 - License and Copyright header
Failed! Guideline description: Where possible, all source code should contain appropriate copyright and license notices as well as information on each contribution. 

Can't find copyright headers at:
- .tractusx
- 	.github/workflows/portal-chart-test.yaml
- 	charts/chart-testing-config.yaml
- 	charts/portal/templates/configmap-backend-postgres-init.yaml
- 	charts/portal/templates/ingress-backend.yaml
- 	charts/portal/templates/ingress-frontend.yaml
- 	charts/portal/templates/secret-backend-external-db.yaml
- 	charts/portal/templates/secret-backend-postgres-init.yaml

More infos: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02

Updates https://github.com/eclipse-tractusx/portal-cd/issues/66

**Comment by evegufy** [comment]
License and Copyright header was added to following files:
- .tractusx
- .github/workflows/portal-chart-test.yaml
- charts/chart-testing-config.yaml

I didn't add the header to the following files because it lead to issues at helm install due to if statement at the beginning: 
charts/portal/templates/configmap-backend-postgres-init.yaml
charts/portal/templates/ingress-backend.yaml
charts/portal/templates/ingress-frontend.yaml
charts/portal/templates/secret-backend-external-db.yaml
charts/portal/templates/secret-backend-postgres-init.yaml

**Comment by evegufy** [comment]
Hi @tomaszbarwicki I actually didn't spent any time or investigate this at all up to now. Thanks for the hint with '---'!
I'd try this notation https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/secrets.yaml#L1
as I just saw that bitnami set headers in bulk two months ago and if it works for them in this case, it'll work for us as well.
